### ISSUE TITLE
Issue with mouse movement

### ISSUE THREAD

**Issue by lachyharris** [george-jensen/record-and-play-pynput#1]
Hi,

Seems to be issues with the mouse movement recording, not seeming to record any movements. Any reason why?

**Comment by george-jensen** [comment]
Hi Lachy!

There is only click based 'movement' capture at the moment. This means the data takes in the click time and location, however it doesn't track the live movement of the cursor.

Is this what you were referring to?

Thanks so much,
George

**Comment by lachyharris** [comment]
Yes that was what I was meaning. Any plan or guidance on how to implement
it? I see it in the pynput documentation but couldn’t get it going to
actually transfer into the json file and playback.

Thanks

**Comment by george-jensen** [comment]
Hi Lachy,

I'll look to add this as an optional feature this weekend, does that timing work alright with you? I'll keep you posted on progress pre-release.

Thanks!

**Comment by lachyharris** [comment]
Hi,

Yeah that’s absolutely fine, no rush at all.

Thanks for getting back to me

**Comment by george-jensen** [comment]
Hi Lachy,

I've just written in functionality for full mouse tracking. Please give it a go and let me know if this is performing how you'd like it to. I've updated the ReadMe describing how to access it, but all you have to do is simply add the optional parameter 'record-all' after the name of your recording, this will record all mouse movement too.

This will now be the standard recommendation, and only very lengthy recordings should avoid using this parameter (as the data file size for recordings of 30+ minutes will start entering the territory of several MB, and some users may not want large data files).

Thank you very much for raising this issue and please let me know if it's working how you want it to. I really appreciate the feedback.

George

**Comment by lachyharris** [comment]
Hi, have realised although it works perfectly, it doesn't suit my needs since I am recording in game which doesn't change x,y since the crosshair stays centered. I have gone to option B, using the numpad keys to record mouse movement using ease of access settings. But your code doesn't seem to detect the numpad keys, any tinkering that can be done to make that work?

Really aprreicated!

**Comment by lachyharris** [comment]
As to my previous message. I have noticed this is likely impossible since the numpad no longer acts as a key at all when in mouse mode. So i am just manually moving pixel values in the created file. My query is if there's a way I could create a command to run a combination of created scripts randomly, so it could play a set of scripts in a random order as a loop until terminated with a hot key. Plan to make an afk loop which isn't detectable by pattern at all.

**Comment by george-jensen** [comment]
Hi Lachy,

I can write a file which will handle this behaviour for you within the next day or two, it'll also require an edit to the 'play.py' file but I can show you where to edit that file too.

I'll get back to you shortly with the result.

Thanks so much,
George

**Comment by george-jensen** [comment]
Hi Lachy,

I've written a file called 'play_random_multiple.py' which I'll attach the code for in the following comment. If you record your multiple recordings individually, and then run this file with all of the recorded filenames as inputs, the script will indefinitely run your multiple recordings in a random order until you hit 'control + C' in the terminal/CMD to cancel.

Please test this out and let me know if it works how you were hoping. Also, I'd advise going in and removing the 2 second right click at the end of each of the data files (after you've recorded), so that you aren't continuously doing this throughout the looping recordings.

I look forward to hearing from you.

Thanks,
George

**Comment by george-jensen** [comment]
Create a file called 'play_random_multiple.py', and copy the below code into the file:

`import random
from pynput.mouse import Button, Controller as MouseController
from pynput.keyboard import Key, Controller as KeyboardController
import time
import json
import sys

n = len(sys.argv)

if n < 2:
    exit("Takes minimum 1 argument - name of recording to play")

# Takes as many input filenames and runs them all indefinitely in a random order
files_to_play = ["data/" + str(sys.argv[i]) +'.txt' for i in range(1, n)]

special_keys = {"Key.shift": Key.shift, "Key.tab": Key.tab, "Key.caps_lock": Key.caps_lock, "Key.ctrl": Key.ctrl, "Key.alt": Key.alt, "Key.cmd": Key.cmd, "Key.cmd_r": Key.cmd_r, "Key.alt_r": Key.alt_r, "Key.ctrl_r": Key.ctrl_r, "Key.shift_r": Key.shift_r, "Key.enter": Key.enter, "Key.backspace": Key.backspace, "Key.f19": Key.f19, "Key.f18": Key.f18, "Key.f17": Key.f17, "Key.f16": Key.f16, "Key.f15": Key.f15, "Key.f14": Key.f14, "Key.f13": Key.f13, "Key.media_volume_up": Key.media_volume_up, "Key.media_volume_down": Key.media_volume_down, "Key.media_volume_mute": Key.media_volume_mute, "Key.media_play_pause": Key.media_play_pause, "Key.f6": Key.f6, "Key.f5": Key.f5, "Key.right": Key.right, "Key.down": Key.down, "Key.left": Key.left, "Key.up": Key.up, "Key.page_up": Key.page_up, "Key.page_down": Key.page_down, "Key.home": Key.home, "Key.end": Key.end, "Key.delete": Key.delete, "Key.space": Key.space}

mouse = MouseController()
keyboard = KeyboardController()

while True:
    current_files_to_play = files_to_play.copy()
    while len(current_files_to_play) > 0:
        random_selection = random.choice(current_files_to_play)
        current_files_to_play.remove(random_selection)
        with open(random_selection) as json_file:
            data = json.load(json_file)
            for index, obj in enumerate(data):
                action, _time= obj['action'], obj['_time']
                try:
                    next_movement = data[index+1]['_time']
                    pause_time = next_movement - _time
                except IndexError as e:
                    pause_time = 1
                
                if action == "pressed_key" or action == "released_key":
                    key = obj['key'] if 'Key.' not in obj['key'] else special_keys[obj['key']]
                    print("action: {0}, time: {1}, key: {2}".format(action, _time, str(key)))
                    if action == "pressed_key":
                        keyboard.press(key)
                    else:
                        keyboard.release(key)
                    time.sleep(pause_time)


                else:
                    move_for_scroll = True
                    x, y = obj['x'], obj['y']
                    if action == "scroll" and index > 0 and (data[index - 1]['action'] == "pressed" or data[index - 1]['action'] == "released"):
                        if x == data[index - 1]['x'] and y == data[index - 1]['y']:
                            move_for_scroll = False
                    print("x: {0}, y: {1}, action: {2}, time: {3}".format(x, y, action, _time))
                    mouse.position = (x, y)
                    if action == "pressed" or action == "released" or action == "scroll" and move_for_scroll == True:
                        time.sleep(0.1)
                    if action == "pressed":
                        mouse.press(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "released":
                        mouse.release(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "scroll":
                        horizontal_direction, vertical_direction = obj['horizontal_direction'], obj['vertical_direction']
                        mouse.scroll(horizontal_direction, vertical_direction)
                    time.sleep(pause_time)
        `

**Comment by george-jensen** [comment]
Create a file called 'play_random_multiple.py', and copy the below code into the file:

`import random
from pynput.mouse import Button, Controller as MouseController
from pynput.keyboard import Key, Controller as KeyboardController
import time
import json
import sys

n = len(sys.argv)

if n < 2:
    exit("Takes minimum 1 argument - name of recording to play")

# Takes as many input filenames and runs them all indefinitely in a random order
files_to_play = ["data/" + str(sys.argv[i]) +'.txt' for i in range(1, n)]

special_keys = {"Key.shift": Key.shift, "Key.tab": Key.tab, "Key.caps_lock": Key.caps_lock, "Key.ctrl": Key.ctrl, "Key.alt": Key.alt, "Key.cmd": Key.cmd, "Key.cmd_r": Key.cmd_r, "Key.alt_r": Key.alt_r, "Key.ctrl_r": Key.ctrl_r, "Key.shift_r": Key.shift_r, "Key.enter": Key.enter, "Key.backspace": Key.backspace, "Key.f19": Key.f19, "Key.f18": Key.f18, "Key.f17": Key.f17, "Key.f16": Key.f16, "Key.f15": Key.f15, "Key.f14": Key.f14, "Key.f13": Key.f13, "Key.media_volume_up": Key.media_volume_up, "Key.media_volume_down": Key.media_volume_down, "Key.media_volume_mute": Key.media_volume_mute, "Key.media_play_pause": Key.media_play_pause, "Key.f6": Key.f6, "Key.f5": Key.f5, "Key.right": Key.right, "Key.down": Key.down, "Key.left": Key.left, "Key.up": Key.up, "Key.page_up": Key.page_up, "Key.page_down": Key.page_down, "Key.home": Key.home, "Key.end": Key.end, "Key.delete": Key.delete, "Key.space": Key.space}

mouse = MouseController()
keyboard = KeyboardController()

while True:
    current_files_to_play = files_to_play.copy()
    while len(current_files_to_play) > 0:
        random_selection = random.choice(current_files_to_play)
        current_files_to_play.remove(random_selection)
        with open(random_selection) as json_file:
            data = json.load(json_file)
            for index, obj in enumerate(data):
                action, _time= obj['action'], obj['_time']
                try:
                    next_movement = data[index+1]['_time']
                    pause_time = next_movement - _time
                except IndexError as e:
                    pause_time = 1
                
                if action == "pressed_key" or action == "released_key":
                    key = obj['key'] if 'Key.' not in obj['key'] else special_keys[obj['key']]
                    print("action: {0}, time: {1}, key: {2}".format(action, _time, str(key)))
                    if action == "pressed_key":
                        keyboard.press(key)
                    else:
                        keyboard.release(key)
                    time.sleep(pause_time)


                else:
                    move_for_scroll = True
                    x, y = obj['x'], obj['y']
                    if action == "scroll" and index > 0 and (data[index - 1]['action'] == "pressed" or data[index - 1]['action'] == "released"):
                        if x == data[index - 1]['x'] and y == data[index - 1]['y']:
                            move_for_scroll = False
                    print("x: {0}, y: {1}, action: {2}, time: {3}".format(x, y, action, _time))
                    mouse.position = (x, y)
                    if action == "pressed" or action == "released" or action == "scroll" and move_for_scroll == True:
                        time.sleep(0.1)
                    if action == "pressed":
                        mouse.press(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "released":
                        mouse.release(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "scroll":
                        horizontal_direction, vertical_direction = obj['horizontal_direction'], obj['vertical_direction']
                        mouse.scroll(horizontal_direction, vertical_direction)
                    time.sleep(pause_time)
        `

**Comment by george-jensen** [comment]
` import random
from pynput.mouse import Button, Controller as MouseController
from pynput.keyboard import Key, Controller as KeyboardController
import time
import json
import sys

n = len(sys.argv)

if n < 2:
    exit("Takes minimum 1 argument - name of recording to play")

files_to_play = ["data/" + str(sys.argv[i]) +'.txt' for i in range(1, n)]

special_keys = {"Key.shift": Key.shift, "Key.tab": Key.tab, "Key.caps_lock": Key.caps_lock, "Key.ctrl": Key.ctrl, "Key.alt": Key.alt, "Key.cmd": Key.cmd, "Key.cmd_r": Key.cmd_r, "Key.alt_r": Key.alt_r, "Key.ctrl_r": Key.ctrl_r, "Key.shift_r": Key.shift_r, "Key.enter": Key.enter, "Key.backspace": Key.backspace, "Key.f19": Key.f19, "Key.f18": Key.f18, "Key.f17": Key.f17, "Key.f16": Key.f16, "Key.f15": Key.f15, "Key.f14": Key.f14, "Key.f13": Key.f13, "Key.media_volume_up": Key.media_volume_up, "Key.media_volume_down": Key.media_volume_down, "Key.media_volume_mute": Key.media_volume_mute, "Key.media_play_pause": Key.media_play_pause, "Key.f6": Key.f6, "Key.f5": Key.f5, "Key.right": Key.right, "Key.down": Key.down, "Key.left": Key.left, "Key.up": Key.up, "Key.page_up": Key.page_up, "Key.page_down": Key.page_down, "Key.home": Key.home, "Key.end": Key.end, "Key.delete": Key.delete, "Key.space": Key.space}

mouse = MouseController()
keyboard = KeyboardController()

while True:
    current_files_to_play = files_to_play.copy()
    while len(current_files_to_play) > 0:
        random_selection = random.choice(current_files_to_play)
        current_files_to_play.remove(random_selection)
        with open(random_selection) as json_file:
            data = json.load(json_file)
            for index, obj in enumerate(data):
                action, _time= obj['action'], obj['_time']
                try:
                    next_movement = data[index+1]['_time']
                    pause_time = next_movement - _time
                except IndexError as e:
                    pause_time = 1
                
                if action == "pressed_key" or action == "released_key":
                    key = obj['key'] if 'Key.' not in obj['key'] else special_keys[obj['key']]
                    print("action: {0}, time: {1}, key: {2}".format(action, _time, str(key)))
                    if action == "pressed_key":
                        keyboard.press(key)
                    else:
                        keyboard.release(key)
                    time.sleep(pause_time)


                else:
                    move_for_scroll = True
                    x, y = obj['x'], obj['y']
                    if action == "scroll" and index > 0 and (data[index - 1]['action'] == "pressed" or data[index - 1]['action'] == "released"):
                        if x == data[index - 1]['x'] and y == data[index - 1]['y']:
                            move_for_scroll = False
                    print("x: {0}, y: {1}, action: {2}, time: {3}".format(x, y, action, _time))
                    mouse.position = (x, y)
                    if action == "pressed" or action == "released" or action == "scroll" and move_for_scroll == True:
                        time.sleep(0.1)
                    if action == "pressed":
                        mouse.press(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "released":
                        mouse.release(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "scroll":
                        horizontal_direction, vertical_direction = obj['horizontal_direction'], obj['vertical_direction']
                        mouse.scroll(horizontal_direction, vertical_direction)
                    time.sleep(pause_time)
`

**Comment by george-jensen** [comment]
`import random
from pynput.mouse import Button, Controller as MouseController
from pynput.keyboard import Key, Controller as KeyboardController
import time
import json
import sys
`
`
n = len(sys.argv)

if n < 2:
    exit("Takes minimum 1 argument - name of recording to play")

# Takes as many input filenames and runs them all indefinitely in a random order
files_to_play = ["data/" + str(sys.argv[i]) +'.txt' for i in range(1, n)]

special_keys = {"Key.shift": Key.shift, "Key.tab": Key.tab, "Key.caps_lock": Key.caps_lock, "Key.ctrl": Key.ctrl, "Key.alt": Key.alt, "Key.cmd": Key.cmd, "Key.cmd_r": Key.cmd_r, "Key.alt_r": Key.alt_r, "Key.ctrl_r": Key.ctrl_r, "Key.shift_r": Key.shift_r, "Key.enter": Key.enter, "Key.backspace": Key.backspace, "Key.f19": Key.f19, "Key.f18": Key.f18, "Key.f17": Key.f17, "Key.f16": Key.f16, "Key.f15": Key.f15, "Key.f14": Key.f14, "Key.f13": Key.f13, "Key.media_volume_up": Key.media_volume_up, "Key.media_volume_down": Key.media_volume_down, "Key.media_volume_mute": Key.media_volume_mute, "Key.media_play_pause": Key.media_play_pause, "Key.f6": Key.f6, "Key.f5": Key.f5, "Key.right": Key.right, "Key.down": Key.down, "Key.left": Key.left, "Key.up": Key.up, "Key.page_up": Key.page_up, "Key.page_down": Key.page_down, "Key.home": Key.home, "Key.end": Key.end, "Key.delete": Key.delete, "Key.space": Key.space}

mouse = MouseController()
keyboard = KeyboardController()

while True:
    current_files_to_play = files_to_play.copy()
    while len(current_files_to_play) > 0:
        random_selection = random.choice(current_files_to_play)
        current_files_to_play.remove(random_selection)
        with open(random_selection) as json_file:
            data = json.load(json_file)
            for index, obj in enumerate(data):
                action, _time= obj['action'], obj['_time']
                try:
                    next_movement = data[index+1]['_time']
                    pause_time = next_movement - _time
                except IndexError as e:
                    pause_time = 1
                
                if action == "pressed_key" or action == "released_key":
                    key = obj['key'] if 'Key.' not in obj['key'] else special_keys[obj['key']]
                    print("action: {0}, time: {1}, key: {2}".format(action, _time, str(key)))
                    if action == "pressed_key":
                        keyboard.press(key)
                    else:
                        keyboard.release(key)
                    time.sleep(pause_time)


                else:
                    move_for_scroll = True
                    x, y = obj['x'], obj['y']
                    if action == "scroll" and index > 0 and (data[index - 1]['action'] == "pressed" or data[index - 1]['action'] == "released"):
                        if x == data[index - 1]['x'] and y == data[index - 1]['y']:
                            move_for_scroll = False
                    print("x: {0}, y: {1}, action: {2}, time: {3}".format(x, y, action, _time))
                    mouse.position = (x, y)
                    if action == "pressed" or action == "released" or action == "scroll" and move_for_scroll == True:
                        time.sleep(0.1)
                    if action == "pressed":
                        mouse.press(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "released":
                        mouse.release(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "scroll":
                        horizontal_direction, vertical_direction = obj['horizontal_direction'], obj['vertical_direction']
                        mouse.scroll(horizontal_direction, vertical_direction)
                    time.sleep(pause_time)
        `

**Comment by george-jensen** [comment]
Create a new file called 'play_random_multiple.py' and copy the below code into it:

`import random
from pynput.mouse import Button, Controller as MouseController
from pynput.keyboard import Key, Controller as KeyboardController
import time
import json
import sys

n = len(sys.argv)

if n < 2:
    exit("Takes minimum 1 argument - name of recording to play")

# Takes as many input filenames and runs them all indefinitely in a random order
files_to_play = ["data/" + str(sys.argv[i]) +'.txt' for i in range(1, n)]

special_keys = {"Key.shift": Key.shift, "Key.tab": Key.tab, "Key.caps_lock": Key.caps_lock, "Key.ctrl": Key.ctrl, "Key.alt": Key.alt, "Key.cmd": Key.cmd, "Key.cmd_r": Key.cmd_r, "Key.alt_r": Key.alt_r, "Key.ctrl_r": Key.ctrl_r, "Key.shift_r": Key.shift_r, "Key.enter": Key.enter, "Key.backspace": Key.backspace, "Key.f19": Key.f19, "Key.f18": Key.f18, "Key.f17": Key.f17, "Key.f16": Key.f16, "Key.f15": Key.f15, "Key.f14": Key.f14, "Key.f13": Key.f13, "Key.media_volume_up": Key.media_volume_up, "Key.media_volume_down": Key.media_volume_down, "Key.media_volume_mute": Key.media_volume_mute, "Key.media_play_pause": Key.media_play_pause, "Key.f6": Key.f6, "Key.f5": Key.f5, "Key.right": Key.right, "Key.down": Key.down, "Key.left": Key.left, "Key.up": Key.up, "Key.page_up": Key.page_up, "Key.page_down": Key.page_down, "Key.home": Key.home, "Key.end": Key.end, "Key.delete": Key.delete, "Key.space": Key.space}

mouse = MouseController()
keyboard = KeyboardController()

while True:
    current_files_to_play = files_to_play.copy()
    while len(current_files_to_play) > 0:
        random_selection = random.choice(current_files_to_play)
        current_files_to_play.remove(random_selection)
        with open(random_selection) as json_file:
            data = json.load(json_file)
            for index, obj in enumerate(data):
                action, _time= obj['action'], obj['_time']
                try:
                    next_movement = data[index+1]['_time']
                    pause_time = next_movement - _time
                except IndexError as e:
                    pause_time = 1
                
                if action == "pressed_key" or action == "released_key":
                    key = obj['key'] if 'Key.' not in obj['key'] else special_keys[obj['key']]
                    print("action: {0}, time: {1}, key: {2}".format(action, _time, str(key)))
                    if action == "pressed_key":
                        keyboard.press(key)
                    else:
                        keyboard.release(key)
                    time.sleep(pause_time)


                else:
                    move_for_scroll = True
                    x, y = obj['x'], obj['y']
                    if action == "scroll" and index > 0 and (data[index - 1]['action'] == "pressed" or data[index - 1]['action'] == "released"):
                        if x == data[index - 1]['x'] and y == data[index - 1]['y']:
                            move_for_scroll = False
                    print("x: {0}, y: {1}, action: {2}, time: {3}".format(x, y, action, _time))
                    mouse.position = (x, y)
                    if action == "pressed" or action == "released" or action == "scroll" and move_for_scroll == True:
                        time.sleep(0.1)
                    if action == "pressed":
                        mouse.press(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "released":
                        mouse.release(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "scroll":
                        horizontal_direction, vertical_direction = obj['horizontal_direction'], obj['vertical_direction']
                        mouse.scroll(horizontal_direction, vertical_direction)
                    time.sleep(pause_time)`

**Comment by george-jensen** [comment]
Create a new file called 'play_random_multiple.py' and copy the below code into it:

```
import random
from pynput.mouse import Button, Controller as MouseController
from pynput.keyboard import Key, Controller as KeyboardController
import time
import json
import sys

n = len(sys.argv)

if n < 2:
    exit("Takes minimum 1 argument - name of recording to play")

# Takes as many input filenames and runs them all indefinitely in a random order
files_to_play = ["data/" + str(sys.argv[i]) +'.txt' for i in range(1, n)]

special_keys = {"Key.shift": Key.shift, "Key.tab": Key.tab, "Key.caps_lock": Key.caps_lock, "Key.ctrl": Key.ctrl, "Key.alt": Key.alt, "Key.cmd": Key.cmd, "Key.cmd_r": Key.cmd_r, "Key.alt_r": Key.alt_r, "Key.ctrl_r": Key.ctrl_r, "Key.shift_r": Key.shift_r, "Key.enter": Key.enter, "Key.backspace": Key.backspace, "Key.f19": Key.f19, "Key.f18": Key.f18, "Key.f17": Key.f17, "Key.f16": Key.f16, "Key.f15": Key.f15, "Key.f14": Key.f14, "Key.f13": Key.f13, "Key.media_volume_up": Key.media_volume_up, "Key.media_volume_down": Key.media_volume_down, "Key.media_volume_mute": Key.media_volume_mute, "Key.media_play_pause": Key.media_play_pause, "Key.f6": Key.f6, "Key.f5": Key.f5, "Key.right": Key.right, "Key.down": Key.down, "Key.left": Key.left, "Key.up": Key.up, "Key.page_up": Key.page_up, "Key.page_down": Key.page_down, "Key.home": Key.home, "Key.end": Key.end, "Key.delete": Key.delete, "Key.space": Key.space}

mouse = MouseController()
keyboard = KeyboardController()

while True:
    current_files_to_play = files_to_play.copy()
    while len(current_files_to_play) > 0:
        random_selection = random.choice(current_files_to_play)
        current_files_to_play.remove(random_selection)
        with open(random_selection) as json_file:
            data = json.load(json_file)
            for index, obj in enumerate(data):
                action, _time= obj['action'], obj['_time']
                try:
                    next_movement = data[index+1]['_time']
                    pause_time = next_movement - _time
                except IndexError as e:
                    pause_time = 1
                
                if action == "pressed_key" or action == "released_key":
                    key = obj['key'] if 'Key.' not in obj['key'] else special_keys[obj['key']]
                    print("action: {0}, time: {1}, key: {2}".format(action, _time, str(key)))
                    if action == "pressed_key":
                        keyboard.press(key)
                    else:
                        keyboard.release(key)
                    time.sleep(pause_time)


                else:
                    move_for_scroll = True
                    x, y = obj['x'], obj['y']
                    if action == "scroll" and index > 0 and (data[index - 1]['action'] == "pressed" or data[index - 1]['action'] == "released"):
                        if x == data[index - 1]['x'] and y == data[index - 1]['y']:
                            move_for_scroll = False
                    print("x: {0}, y: {1}, action: {2}, time: {3}".format(x, y, action, _time))
                    mouse.position = (x, y)
                    if action == "pressed" or action == "released" or action == "scroll" and move_for_scroll == True:
                        time.sleep(0.1)
                    if action == "pressed":
                        mouse.press(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "released":
                        mouse.release(Button.left if obj['button'] == "Button.left" else Button.right)
                    elif action == "scroll":
                        horizontal_direction, vertical_direction = obj['horizontal_direction'], obj['vertical_direction']
                        mouse.scroll(horizontal_direction, vertical_direction)
                    time.sleep(pause_time)
```

**Comment by yingusb** [comment]
Is there anyway i could modify your code so that it would work with fps games without the numpad thing?
